dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test --keepdb
deploy:
  provider: heroku
  app: https://decide-abdelha.herokuapp.com/
  strategy: git
  api_key:
    secure: raA+tLYiE4HlUSaqhXNxTcoe1WV9oMqtvhd7OR/1ySD1BkfWBbsL05mBYBs7DDAJ80WzoMamuU0YukdfZXjKf5wITwDWA3PFSuA0+h/aSXkU97fxh3+57UzTqLdQu7xgvJI1pST90MqMRxpdQnF9S/7Eeu2/I4i4CnSzfkhIQpzhKn+G4Wz09/QYIERoJ+0tBEuHmK4OhOeSgWLpZE98QrFeFRgc6zd+eI3I/rgiHZpSLfOpCsDcVG2GZNJ/6s6J/cxSSBe3ORhkaI62ixmjr6cjs9RwZ8kyDksROcKOW6RbHfTQ+whaG43oom14ER7RRtoscvoq332Ij5PFjwnW79IoxXv024aZjhEGJhN/xTvqu9m0d3ynVUVpKT4t0OlpzmIsTLRVIsmr8WFfR+21JzKRAxohFgTGJLPozzq7HupI/nnqQW3iP1g2H2BcDylR5s10+6dzlWXO/op5fxgEEGeCtaeaGQwzAtUQ/4X90rOADzqMnuxGvM8e4Ri07unQqwpzgodxvkvrox54idTBe5MnhtHd/hK55DxgOcKSuSeMHyt7QHAXnmrIe7bYb4JWudBMjz+3pUUcisjdSnsRndkBgqWHUqeo+SL2am6ot7sJAPD259clO2d/9s0+sOdvqhkO2E80gLLyTLxU2P88Tii3EMmC7XcwjxjP9umUL28=
